### ISSUE TITLE
Plotting ...

### ISSUE THREAD

**Issue by mjhmilla** [sheim/vibly#12]
Nice work on the animation Charlotte! I just tried to run 'viability_plot.py' and I get the error message below. As a note I am calling python3 from the command line, I am not using this through Anaconda. Am I missing something?

Notes:
1. I'm running this from a terminal in the slippy folder. I've changed the path to "data/low_res_slip.npz"

2. This is the error I get in full:

python3 demos/viability_plot.py 
Traceback (most recent call last):
  File "/home/mjhmilla/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 440, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demos/viability_plot.py", line 5, in <module>
    data               = np.load('data/low_res_slip.npz')
  File "/home/mjhmilla/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 443, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'data/low_res_slip.npz' as a pickle

**Comment by sheim** [comment]
One issue is my fault: I've changed how data is saved to streamline things a bit more. However, it doesn't look like this is what your issue is...

I'll look into it a bit more after lunch, but make sure you have the pickle package. that would be my first guess. For reference, I have matplotlib version 3.0.3 and numpy version 1.16.2 and python 3.7.3

data change:
I no longer pass around "s_grid" and "a_grid" in functions, and instead pass around the dict `grids`, with keys `states` and `actions`. Hence, I also save as such. This requires a bit of fiddling during loading, and in particular the low-res dataset hasn't been updated. I'll handle this after lunch.

**Comment by sheim** [comment]
Do you still have this issue?

**Comment by mjhmilla** [comment]
I just updated my git repository so that it mirrors yours exactly (git fetch upstream, git reset --hard upstream/master, git clean -f -d). I still do see the same error. 

Here's my system setup:

python: 3.6.7
numpy: 1.16.3
matplotlib: 3.0.3
pickle: 4.0

From what I see online there were some additions done to pickle between python 3.6 and 3.7, so that might explain the error. I'll try updating python.

**Comment by mjhmilla** [comment]
Updating python did not fix the problem. This is not a pressing issue, so I'm going to leave this error for now.

**Comment by sheim** [comment]
Okay. Not sure when I'll get to it, and main thing is I'm not sure how to
reproduce it since this works on my box. I'll leave the issue open, will
probably not get to this till after I get back from DW

**Comment by sheim** [comment]
Is this still an issue?

**Comment by mjhmilla** [comment]
I've been distracted by other work so I haven't yet checked. I'll be sure
to respond once I've hopped back onto vibly.
Matt

**Comment by sheim** [comment]
No worries. I don't think it's an issue, also because we'll be doing other things for plotting. If it is an issue, just re-open this and ping me (or a new issue). I'm just trying to close stale issues : )
